server:
  port: 8080

jwt:
  secret: a-string-secret-at-least-256-bits-long

spring:
  application:
      name: API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders: "*"
          routes:
            - id: auth-service
              uri: http://104.211.95.241:8080
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /api/auth/${segment}

            - id: zone-service
              uri: lb://ZONE-SERVICE
              predicates:
                - Path=/api/zones/**
              filters:
                - name: AuthenticationFilter

            - id: sensor-telemetry-service
              uri: lb://SENSOR-TELEMETRY-SERVICE
              predicates:
                - Path=/api/sensors/**
              filters:
                - name: AuthenticationFilter

            - id: automation-service
              uri: lb://AUTOMATION-SERVICE
              predicates:
                - Path=/api/automation/**
              filters:
                - name: AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/