server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DiilaNa/Automated_Greenhouse_Management_System-Microservices.git
          search-paths: config-repo

#http://localhost:8888/application/default  check this url to confirm config server is running

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

