server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DiilaNa/Automated_Greenhouse_Management_System-Mirco_Services_Architecture.git
          search-paths: config-repo